version: '3.8'
services:
  api:
    container_name: medium-clone-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: medium-clone-db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgres:
    name: nest-db

networks:
  postgres:
    driver: bridge
